### ISSUE TITLE
DPI issue in Halation

### ISSUE THREAD

**Issue by UlyssesWu** [rinkako/Slyvia#1]
![halation](https://user-images.githubusercontent.com/4312781/28962782-658c6f9e-7939-11e7-8bcb-b5809561cbf3.png)

如图所示。测试缩放：225%；分辨率：2736*1824

**Comment by rinkako** [comment]
这应该是原生UI存在的问题，Halation本质上是一个WinForm应用程序，这个地方是使用了ListBox控件，我不确定是否是因为修改了绘制lineitem的方法从而导致高分辨率下出现了这样的bug。不过修复起来应该还蛮麻烦的，我的规划是后期改用WPF重做一下Halation，毕竟现在还是太简陋了。而且用WPF做的话，可以支持一些效果的实时测试。

**Comment by chubbyerror** [comment]
> 这应该是原生UI存在的问题，Halation本质上是一个WinForm应用程序，这个地方是使用了ListBox控件，我不确定是否是因为修改了绘制lineitem的方法从而导致高分辨率下出现了这样的bug。不过修复起来应该还蛮麻烦的，我的规划是后期改用WPF重做一下Halation，毕竟现在还是太简陋了。而且用WPF做的话，可以支持一些效果的实时测试。

look at [here](https://docs.microsoft.com/zh-cn/dotnet/framework/winforms/high-dpi-support-in-windows-forms) or [csdn](https://bbs.csdn.net/topics/392396889)

it is fixed at 2017/05/16.

**Comment by UlyssesWu** [comment]
首先恭喜本Repo喜提新开发者。

不过，@chubbyerror 的建议并不能解决此问题。这个问题并不像作者所说，是“原生UI存在的问题”，而是编码上的遗漏导致，详见 #7 。当然，作者若有意把编辑器用WPF重写是最好的（虽说编辑器不是执行引擎，使用WinForm的话还有望在非Windows平台挣扎一下）。

由于 #6 问题的存在，每次测试我都不得不新开一个工程，共计开了11个（

应用 #7 后的效果图：

![yuri_dpi](https://user-images.githubusercontent.com/4312781/42921571-34bb7dfa-8b4f-11e8-965e-749c5881a5d3.png)

**Comment by chubbyerror** [comment]
@UlyssesWu [这个问题](https://github.com/rinkako/YuriAVGEngine/issues/6) 你有什么心得吗……………… 男友要做avg我正在选引擎，你那边我也下载看看

**Comment by rinkako** [comment]
@chubbyerror 其实我还是没复现出这个问题…如果你能说一下出现问题时的操作步骤那就最好了~
虽然作为这个项目的开发者似乎说这句话立场不太对，不过你真的要用这个做一个游戏产品吗？Yuri项目的初衷是研究avg引擎底层的一些原理，所以如果你的目标是直接做一个游戏出来的话，那你可能会在折腾这个引擎上花费比较多的时间，这个对产品来说是比较忌讳；如果你本身对技术有兴趣的话，那自然是很适合的w。当然，yuri本身做普通的avg完全没问题，我之前就做过demo了，最近也在用她做一个解密类的游戏。
不过聊了这么多为什么我们几个人不加个好友聊个够呢（笑，my Q is 307359770.
现在变成社畜了，能够给这个项目贡献代码的时间也是非常稀有。总之能有喜欢她的人，我是非常开心

**Comment by UlyssesWu** [comment]
感谢作者接受了PR。至于 #6 问题是确实存在的，就等待作者去修复吧。（为什么issue又Open了……）
加好友倒是先留下联系方式啊（逃

**Comment by chubbyerror** [comment]
@UlyssesWu  > 感谢作者接受了PR。至于 #6 问题是确实存在的，就等待作者去修复吧。（为什么issue又Open了……）
加好友倒是先留下联系方式啊（逃

好啊我的地址是中国重庆市渝中区(拿出盾牌防止被打死。
好啦我发个邮箱吧，还在古板单位上班没法开QQ什么的，invsibleelephant@foxmail.com

**Comment by UlyssesWu** [comment]
@chubbyerror 
关于制作AVG的引擎：
若要出于跨平台考虑，我建议采用Unity，有一些方案如[Fungus](https://assetstore.unity.com/packages/templates/systems/fungus-34184)或[YarnSpinner](https://github.com/thesecretlab/YarnSpinner)（我都还没试过，感兴趣可以看看）。更高级的收费的方案比如[《宴》](https://assetstore.unity.com/packages/templates/systems/utage3-unity-text-adventure-game-engine-version3-80727)（日厂出品）。
传统日厂引擎如krkr2/krkrz，可能是现在功能和插件最多的引擎，我个人不推荐，TJS脚本的学习曲线太高了；NS倒是挺简单，但演出效果太少，不过仍会有《水仙》这样的精品出现。
如果还想更简单，可去steam买专门的文字游戏设计工具（我见过两三款，优劣看评价就知道了）。
我喜欢Yuri的WPF设计，不过还是得有空研究才行（

**Comment by chubbyerror** [comment]
@UlyssesWu 你说的这些我都看过，那两个自定义功能不足还是暂时放一放吧，男友那边有个奇怪的需求（精灵可以点击和点击产生变化），所以那几个标准引擎改造难度太大了。Unity端太大了，不方便，先用这个小巧的试试看吧。

**Comment by UlyssesWu** [comment]
看起来算不上是“奇怪的需求”，我相信Unity的方案肯定都能做（没听说过VS都装了还会嫌Unity大的）。
看来本项目真的可以喜提新开发者了（

**Comment by rinkako** [comment]
@chubbyerror 嘛你决定我当然是很开心的，总之你如果遇到什么坑点可以直接找我，我的Q留言在上面了已经。不过平时也要上班，估计也是晚上才能回复就是（
