### ISSUE TITLE
圈一个Typo

### ISSUE THREAD

**Issue by inactive0v0** [rinkako/Slyvia#10]
![QQ截图20190914195356](https://user-images.githubusercontent.com/28744819/64907767-6fc01100-d729-11e9-81f8-59f0fcb8702e.png)

**Comment by rinkako** [comment]
Fix typo with commit [ae8b1d3](https://github.com/rinkako/YuriAVGEngine/commit/ae8b1d3913583524fa0d12207e40b7db2cb89839) and  [2cc7c5c](https://github.com/rinkako/YuriAVGEngine/commit/2cc7c5cbe11094804db1f491cab4b475044fad2a)⭐⭐
