### ISSUE TITLE
Need Yuriri Script Sample

### ISSUE THREAD

**Issue by UlyssesWu** [rinkako/Slyvia#2]
尽管Wiki中写了这么多Yuriri的设计思路，但整个repo中并没有任何用Yuriri编写的脚本，只有Halation的Project，而且还无法转换成Yuriri脚本。
希望给出Yuriri脚本的示例。

**Comment by rinkako** [comment]
可以用Halation打开DEMO游戏Edelweiss根目录下的game.yrproj，可以看到所有的游戏逻辑，然后用Halation编译，可以在Scenario文件夹里看到生成的Yuri脚本和Yuriri-IL中间代码

**Comment by UlyssesWu** [comment]
好的，看到了。
那么再问一下，以Yuriri的语法，目前是不能做到类似于《逆转裁判》那样的对话中控制符（比如只显示一行，点击后再显示下一行；比如字体的加粗和变色；比如在“大婶儿”说话的时候，打字机速度逐步加快的效果）的吧？
按Yuriri语法大概会是这个样子：
```
[
大婶儿我啊@b年轻@n的时候也是@f巴拉巴拉
@ff巴拉巴拉巴拉巴拉巴拉巴拉小魔仙@skip
]
```
（以上控制符纯属YY，b=粗体，n=正常体，f=快速，ff=超快速，skip=无须点击直接进入下一句话）

**Comment by rinkako** [comment]
这是一个转义问题。Yuri在设计的时候是预留了这个可能性的，具体部分是在`Yuri.PlatformCore.UpdateRender`中的`DialogToRuns`方法，她会将对话文本分割成趟，并处理可能的转义，在这个方法里，你可以看到目前是实现了在对话文字中插入显示变量值的功能，实际上，实现你刚刚说的那些特效，又或者说想实现任何功能，就需要修改这个位置，来加入自定义的解析转义符号触发的效果。

**Comment by UlyssesWu** [comment]
我不是编译原理的大触，本科勉强及格的我再问一个naive的问题：为什么使用这种方式，而不是设计成语法的一部分呢？（因为上面我举的例子有点像Razor，Razor能够在HTML中分辨出程序代码，使得它相对于PHP之类的语法显得十分简洁）

**Comment by rinkako** [comment]
设计成语法的话，就意味着Yuri Interpreter需要理解这些可以出现在文本中任意位置的修饰符（请允许我暂时用这个词来称呼她们），这会导致原本 G -> [ 对话内容（终结符） ] 这样一个候选式变成了 G -> [ 对话内容（非终结符） ]、对话内容（非终结符）-> 修饰符闭包 单纯对话句子（终结符）修饰符闭包，而修饰符闭包这个非终结符又要继续推导是单纯对话句子、修饰符终结符、还是空串……这样下来整棵语法分析树会非常复杂。关键是，这么做的话并没有必要，因为就算这样做，在编译阶段就确定了对话修饰符的功能，最终这个功能如何演绎成前端效果，还是要在运行时才能确定的，因此我的做法就是，所有修饰符都丢到运行时再解析（在DialogToRuns里，你可以看到有一个修饰符我实现了，就是**\|**修饰符，用于停顿）。

所以我的想法简单的说就是：1、将修饰符变成语法，会让编译器变得复杂；2、修饰符在编译阶段确定了修饰符的功能所减少的性能损耗几乎忽略不计，因为这只是节约了运行时对一条正在显示的语句做一次扫描而已

当然，这些都是我自己个人愚见~

**Comment by UlyssesWu** [comment]
非常感谢巨巨的解答。我觉得这个的意义并不是说提高效率，而是把控制细化到 _字_ 的级别而不是目前 _对话_ 的级别——在每两个字之间都可以使用任何“动作语法”。

我自(ban)己(men)学(nong)习(fu)的Yuriri的方言的词法分析过程有限地实现了这样的功能。
事实上，我或许会搞成一个语法非常类似于Yuriri的简易的解释型语言（白糟蹋了Yuri的设计

![IronYuri](https://user-images.githubusercontent.com/4312781/28996598-8d129658-7a36-11e7-82d3-8e003b2e00f6.png)

**Comment by rinkako** [comment]
我觉得都OK的，事实上，将修饰符的功能延后到运行时处理，理论上来说只要前端渲染可以支持，也是可以做到按字级别的控制，比如说，@b是粗体的话，你只需要在运行时读取到@b修饰符时，通过某些手段来让程序在渲染文字是用粗体处理就好了。当然，你这样的方式也是完全没问题的，不过你要注意下转义问题，因为@b虽然是粗体标记，但有特殊的情况就是用户需要在屏幕上就是现实出@b这两个字符

**Comment by UlyssesWu** [comment]
直接要求所有文本中的`@`使用`＠`（全角），我们懒人是这样的（

**Comment by rinkako** [comment]
其实处理这个问题还是很简单的，要求@要以\@来表达就好了，然后\要用\\来表达，其实就是标准转义。当然，事实上出现这些情况都是极低概率的……完全可以通过用户手册来限定

**Comment by UlyssesWu** [comment]
上面也提到了，文本中间夹杂的不是只在文本中间修饰符，而是能够在文本中间使用 **所有** 动作语法，包括切换立绘表情、BGM等（比如《逆转裁判》系列犯人崩溃时会在吐出某几个字的瞬间变脸）。当然我这也是属于老考虑一些 _极低概率的_ 情况了。

东施效颦的Yuriri方言语法：
```
[
大婶儿我啊 @b 年轻 @n 的时候也是 @f 巴拉巴拉 @a(Name="大婶儿", Face="Angry", vid=2)
@ff 巴拉巴拉巴拉巴拉巴拉巴拉小魔仙 @skip
]
```

![IronYuri2](https://user-images.githubusercontent.com/4312781/28996822-979d3382-7a39-11e7-94f2-9c4282882b74.png)

**Comment by rinkako** [comment]
啊，我明白你的意思了，你这个是在dialog里内嵌了命令的做法。这个我倒是没考虑过，不过实现起来应该挺有意思的ww，期待你做出的效果
