### ISSUE TITLE
源码中很多这些部分报错，说没有定义fr，fg,fb等等，请问是什么地方配置的有问题么

### ISSUE THREAD

**Issue by fengshuitm** [rinkako/Slyvia#4]
if (Byte.TryParse(CFontColorItem[0], out byte fr) &&
                Byte.TryParse(CFontColorItem[1], out byte fg) &&
                Byte.TryParse(CFontColorItem[2], out byte fb))

**Comment by rinkako** [comment]
请使用VS 2017。这个是C# 7.0的新特性，即在函数调用的时候声明out变量。如果不用2017版，可以把fr这几个byte变量先定义好，然后在这里out fr传进去就好了
