### ISSUE TITLE
请问这个报错得怎么改啊，其他地方都改成适应vs2015了

### ISSUE THREAD

**Issue by fengshuitm** [rinkako/Slyvia#5]
(int L5_Chinese, int L7_Japanese, int L8_Korea) = StatisticsWindow.GetChracterLength(orgText);

**Comment by fengshuitm** [comment]
我查到了。。。又是Net7.0的新概念。。。

**Comment by fengshuitm** [comment]
看来我还是上2017算了。。。

**Comment by rinkako** [comment]
这个是同样的问题，在外面定义好变量就好，而不是在函数调用时定义
