### ISSUE TITLE
EN:When will there be a user manual?

### ISSUE THREAD

**Issue by dyxang** [rinkako/Slyvia#9]
CN:用户手册什么时候会有呢？

**Comment by rinkako** [comment]
I'm afraid that it is too busy for me to finish a user manual now  :(
But there is a sample game project may help you to understand how to build a simple avg game using this prototype engine. Download the sample game project `Edelweiss` and use Halation to open `game.yrproj` to read game scripts.
Edelweiss sample project can be downloaded from: https://pan.baidu.com/s/1hsFZTbu

**Comment by dyxang** [comment]
@rinkako
CN: 謝謝，還是希望會有用戶手冊
EN: Hope to launch user manual
